### ISSUE TITLE
Hi, I have a question about code 

### ISSUE THREAD

**Issue by olccihyeon** [tmlabonte/last-layer-retraining#1]
Hello. I'm checking the reproduction to use it as a baseline, and there are a few points in the code that I'm wondering about.

In the case of CelebA, if you pass 500 steps and 20 epochs as arguments, 20 epochs will end faster, so 500 steps will not be executed as in the paper.
I found that the resnet model does not get the weight when only args.weight is passed to early_stop_model. I think it should be loaded with load_weights related to model_class.
The following code section needs to be modified.
early_args = deepcopy(disagreement_args)
early_args.weights = early_stop_weights
print("early_args.weights: ", early_args.weights)
early_stop_model = model_class(early_args)
print("early_stop_model : ", early_stop_model)
As I mentioned last time, I think the positions of early_stop_model and model have been swapped in the process of calculating disagreements.
I think you should update it to reflect the three points so that there is no confusion.

**Comment by tmlabonte** [comment]
Hi, all three of these points will be resolved when the updated code is posted along with the camera-ready version next week. Thanks!
